### ISSUE TITLE
Restarting with the 'test' intergration produces an error (but everything works)

### ISSUE THREAD

**Issue by fallaciousreasoning** [concierge/Concierge#237]
Steps to reproduce

1. Clone Concierge
2. Run Concierge (preferably with the debug flag for more useful output) with the test integration
3. Type /restart

Observer Concierge restart and throw up.
4. Cry because everything is a lie :'(

Observed output is below (the error is at the very end)
```
C:\Dev\concierge-test>node main.js --debug
Debug mode enabled.
No integrations specified, defaulting to 'test'.
   ____                 _                           _           _
  / ___|___  _ __   ___(_) ___ _ __ __ _  ___      | |__   ___ | |_
 | |   / _ \| '_ \ / __| |/ _ \ '__/ _` |/ _ \_____| '_ \ / _ \| __|
 | |__| (_) | | | | (__| |  __/ | | (_| |  __/_____| |_) | (_) | |_
  \____\___/|_| |_|\___|_|\___|_|  \__, |\___|     |_.__/ \___/ \__|
                                   |___/
 4.0.0-beta.2.0.3
------------------------------------
Starting system...
Loading modules...
Loading module 'config'...
Loading Succeeded
Loading system configuration...
Loading module 'creator'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\creator\config.json".
Loading module 'help'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\help\config.json".
Loading module 'kpm'...
Loading Succeeded
Loading module 'ping'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\ping\config.json".
Loading module 'restart'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\restart\config.json".
Loading module 'shutdown'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\shutdown\config.json".
Loading module 'test'...
Loading Succeeded
Loading module 'update'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\update\config.json".
Starting integrations...
Loading integration 'test'...
System has started. Hello World!
Concierge-bot> /restart
Admin: restart procedure requested.
Admin: do you wish to restart?
Concierge-bot: What do you think.
Admin: interpreting vauge answer as 'yes'.
Concierge-bot: nononononono.
Admin: stalemate detected. Stalemate resolution associate please press the stalemate resolution button.
Concierge-bot: I've removed the button.
Admin: restarting anyway.
Concierge-bot: nooooooooooo.....
Admin: Concierge-bot Rebooting. Please wait for restart to complete.

Unloading module "help".
Unloading module "ping".
Unloading module "shutdown".
Unloading module "update".
Unloading module "restart".
Unloading module "kpm".
Unloading module "creator".
Unloading module "test".
Unloading module "config".
Concierge-bot has shutdown.
   ____                 _                           _           _
  / ___|___  _ __   ___(_) ___ _ __ __ _  ___      | |__   ___ | |_
 | |   / _ \| '_ \ / __| |/ _ \ '__/ _` |/ _ \_____| '_ \ / _ \| __|
 | |__| (_) | | | | (__| |  __/ | | (_| |  __/_____| |_) | (_) | |_
  \____\___/|_| |_|\___|_|\___|_|  \__, |\___|     |_.__/ \___/ \__|
                                   |___/
 4.0.0-beta.2.0.3
------------------------------------
Starting system...
Loading modules...
Loading module 'config'...
Loading Succeeded
Loading system configuration...
Loading module 'creator'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\creator\config.json".
Loading module 'help'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\help\config.json".
Loading module 'kpm'...
Loading Succeeded
Loading module 'ping'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\ping\config.json".
Loading module 'restart'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\restart\config.json".
Loading module 'shutdown'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\shutdown\config.json".
Loading module 'test'...
Loading Succeeded
Loading module 'update'...
Loading Succeeded
No or invalid configuration file found at "C:\Dev\concierge-test\modules\update\config.json".
Starting integrations...
Loading integration 'test'...
System has started. Hello World!
"test" threw up. <unknown> is now covered in sick.
TypeError: Cannot read property 'commandHistory' of null
    at command.listener (C:\Dev\concierge-test\modules\test\test.js:58:27)
    at Cli.parse (C:\Dev\concierge-test\node_modules\cline\index.js:320:35)
    at Cli.<anonymous> (C:\Dev\concierge-test\node_modules\cline\index.js:182:18)
    at Cli.defaultFn (C:\Dev\concierge-test\node_modules\cline\index.js:53:13)
    at Cli.fn (C:\Dev\concierge-test\node_modules\cline\index.js:217:23)
    at Interface.<anonymous> (C:\Dev\concierge-test\node_modules\cline\index.js:148:18)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:239:10)
    at Interface._line (readline.js:585:8)
    at Interface._ttyWrite (readline.js:862:14)
    at ReadStream.onkeypress (readline.js:126:10)
    at emitTwo (events.js:106:13)
    at ReadStream.emit (events.js:191:7)
    at emitKeys (internal/readline.js:389:14)
    at undefined.next (native)
    at ReadStream.onData (readline.js:972:36)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at TTY.onread (net.js:548:20)

Concierge-bot>
```

**Comment by mrkno** [comment]
Can you post your `modules/test/config.json`
