### ISSUE TITLE
hubot Update

### ISSUE THREAD

**Issue by mrkno** [concierge/Concierge#251]
Since initial hubot support was implemented, many features such as middleware have been introduced in Concierge. The equivilant features have sub-optimal implementations within the hubot loader which could be replaced with their new Concierge counterparts.

- Middleware
- Catch all
- Before
- After
- Events
- Help

**Comment by p0358** [comment]
I'll add this to here:
```
debug: TypeError: Instance is not a constructor
    at Robot.load (/var/www/Concierge/core/modules/hubot/robot.js:389:75)
    at /var/www/Concierge/core/modules/modules.js:161:40
    at undefined.next (native)
    at step (/var/www/Concierge/core/modules/modules.js:1:260)
    at /var/www/Concierge/core/modules/modules.js:1:420
```

**Comment by mrkno** [comment]
What hubot script caused this error? I've seen it before but haven't had time to investigate. The majority of hubot scripts should at least load, even if they don't function fully.

**Comment by p0358** [comment]
I can't really tell, I tried disabling them all and enabling one by one using kpm to quickly test now, but none gave the error during loading, but `hubot-speed-test` was giving kpm's response that it couldn't get loaded, even though I got info message above it that it was loaded.
I'll later clone a fresh Concierge and copy each module one after another to test it.

**Comment by mrkno** [comment]
Interesting, that would be a regression if kpm was saying that something loaded when it didn't. Note that if you are copying modules across to the latest clone, ensure modules like kpm are up-to-date first. As much as I tried to ensure there were not many breaking changes some backwards incompatibilities in #270 were unavoidable.
