### ISSUE TITLE
Crash with --log CLI parameter

### ISSUE THREAD

**Issue by p0358** [concierge/Concierge#266]
Have a look:
```shell
$ node main.js --debug --log --timestamp --language pl test
warn: Locale set to "pl".
warn: Log level set to "debug".
warn: Timestamps enabled.
warn: File logging mode enabled.
2017-05-24T15:56:34.476Z - error: Error: "debug" has an invalid type "string" when "boolean" was expected.
    at checkType (/var/www/Concierge/core/startup/exports.js:18:15)
    at module.exports (/var/www/Concierge/core/startup/exports.js:42:21)
    at Object.<anonymous> (/var/www/Concierge/core/startup/startup.js:93:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

!CORE! critical error was unhandled (1, NONE). Please report this to developers.
```
```shell
$ node main.js --debug 1 --log --timestamp --language pl test
warn: Locale set to "pl".
warn: Log level set to "debug".
warn: Timestamps enabled.
warn: File logging mode enabled.
2017-05-24T15:56:51.376Z - error: Error: "debug" has an invalid type "string" when "boolean" was expected.
    at checkType (/var/www/Concierge/core/startup/exports.js:18:15)
    at module.exports (/var/www/Concierge/core/startup/exports.js:42:21)
    at Object.<anonymous> (/var/www/Concierge/core/startup/startup.js:93:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

!CORE! critical error was unhandled (1, NONE). Please report this to developers.
```
```shell
$ node main.js --debug debug --log --timestamp --language pl test
warn: Locale set to "pl".
warn: Log level set to "debug".
warn: Timestamps enabled.
warn: File logging mode enabled.
2017-05-24T15:57:01.052Z - error: Error: "debug" has an invalid type "string" when "boolean" was expected.
    at checkType (/var/www/Concierge/core/startup/exports.js:18:15)
    at module.exports (/var/www/Concierge/core/startup/exports.js:42:21)
    at Object.<anonymous> (/var/www/Concierge/core/startup/startup.js:93:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

!CORE! critical error was unhandled (1, NONE). Please report this to developers.
```
```shell
$ node main.js --debug --timestamp --language pl test
warn: Locale set to "pl".
warn: Log level set to "debug".
warn: Timestamps enabled.
2017-05-24T15:57:14.983Z - warn:
   ____                 _                           _           _
  / ___|___  _ __   ___(_) ___ _ __ __ _  ___      | |__   ___ | |_
 | |   / _ \| '_ \ / __| |/ _ \ '__/ _` |/ _ \_____| '_ \ / _ \| __|
 | |__| (_) | | | | (__| |  __/ | | (_| |  __/_____| |_) | (_) | |_
  \____\___/|_| |_|\___|_|\___|_|  \__, |\___|     |_.__/ \___/ \__|
                                   |___/
 4.4.1
------------------------------------
[...]
```

**Comment by mrkno** [comment]
Whoops, that seems like a slight oversight on my part.
```js
if (opts.log && checkType(opts, 'debug', 'boolean')) {
```
should be
```js
if (opts.log && checkType(opts, 'log', 'boolean')) {
```
